# Oldest OS X image in TravisCi at the moment is 10.10
os: osx
osx_image: xcode9.3
language: node_js
node_js:
  - '8'

before_install:
  # OS extra info
  - sw_vers
  - uname -a
  - go version
  - node --version
  - python --version
  - which python
  - pyenv install 3.5.0
  - pyenv versions
  - ls -la $HOME/.pyenv/shims
  - export GOPATH="${HOME}/.go"
  - export GOROOT="$(brew --prefix golang)/libexec"
  - export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
  - test -d "${GOPATH}" || mkdir "${GOPATH}"
  - test -d "${GOPATH}/src/github.com" || mkdir -p "${GOPATH}/src/github.com"
  - go get github.com/itchio/gothub
  - gothub --version
  # Install Python 2 pip, ensure pip installed packages are found first
  # Python 2 installation and path priority in Travis OS X is a bit of a mess
  # https://github.com/travis-ci/travis-ci/issues/4194 
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - sudo python get-pip.py
  - rm get-pip.py
  # - sudo pip install --upgrade pip setuptools wheel
  # https://github.com/pypa/pip/issues/3165
  - sudo -H pip install --ignore-installed six
  - sudo -H pip install --ignore-installed mock
  # Original problem is old version of "six" package lingering around
  # https://github.com/testing-cabal/mock/issues/337
  - export PYTHONPATH=/Library/Python/2.7/site-packages:$PYTHONPATH
  - python -c "import sys; print(sys.path)"
  - python -c "from six import wraps"

  # Install Python 3.5 with pip, and check versions
  - pyenv install 3.5.0
  # - pyenv global 3.5.0
  # - sudo pip3.5 install --upgrade pip

  - brew install libcouchbase
  - PATH=/usr/local/bin:$PATH
  - echo $PATH

  # Install Python packages (built with Python 3, tests for 2 and 3)
  - pyenv global system
  - sudo python -m pip install --ignore-installed six
  - sudo python -m pip install --ignore-installed mock
  - sudo python -m pip install coverage
  - sudo python -m pip install requests
  - pyenv global 3.5.0
  - pip3.5 install coverage
  - pip3.5 install requests
  - pip3.5 install coveralls
  #- pip3 install pydocstyle
  - pip3.5 install mkdocs
  # We need a newer unreleased version of PyInstaller for Python 3.5
  - pip3.5 install https://github.com/pyinstaller/pyinstaller/archive/964547cd92cabe28150d52c2ca809de74a5ddbaa.zip

  # Check Python, pip and package versions
  - pyenv global system
  - python -c "import sys; print(sys.executable)"
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python -m pip --version
  - python -m pip freeze
  - pyenv global 3.5.0
  - python3.5 -c "import sys; print(sys.executable)"
  - python3.5 --version
  - python3.5 -c "import struct; print(struct.calcsize('P') * 8)"
  - pip3.5 --version
  - pip3.5 freeze
  - pyinstaller --version

  # Travis make takes > 10 minutes, so need to increase wait
  - node --version
  - node -p "process.arch"
  - npm --version

# Build and pack Ardublockly
install:
  - pyenv global system
  - cd blockly && python build.py && cd ../
  - pyenv global 3.5.0
  - python3.5 package/build_docs.py
  - python3.5 package/build_pyinstaller.py mac
  - cd package/electron && npm install && cd ../../
  - cd package/electron && npm run release && cd ../../
  - python3.5 package/pack_ardublockly.py
  - du -sk releases/
  - ls -la releases/
  - mv releases/*.zip blockly-for-sensebox_v${TRAVIS_TAG}_osx.zip

# Run the tests in both Python 2 and 3
# script:
#   - python -m coverage run ardublocklyserver/tests/run_all.py
#   - python -m coverage report
#   - python3 -m coverage run ardublocklyserver/tests/run_all.py
#   - python3 -m coverage report
  #- pydocstyle ardublocklyserver --match-dir='ardublocklyserver'

after_success:
  - if [[ ! -z "$TRAVIS_TAG" ]]; then
      echo "Build triggered by a tag";
      gothub upload \
        -u sensebox \
        -r ardublockly-1 \
        -t $TRAVIS_TAG \
        -n blockly-for-sensebox_v${TRAVIS_TAG}_osx.zip \
        -f releases/blockly-for-sensebox_v${TRAVIS_TAG}_osx.zip
    fi
